  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: myapp
    namespace: homework
    labels:
      app: nginx
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: my-nginx
          image: tptjelissei/nginx-test:latest
          ports:
          - containerPort: 80