apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: homework
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31234